POST http://localhost:6969/app/signup
Content-Type: application/json

{
    "firstName": "Julian",
    "middleName": "E",
    "lastName" : "Espinoza",
    "email" : "je688433@gmail.com",
    "username" : "Frosty",
    "password" : "1234"
}